{% set name = "event-model" %}
{% set version = "1.21.0" %}
{% set sha256 = "4c0c6ce9db71fb022f38b5ee6c0c55114851dd07bdfe08a5c54bff9317ce1446" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - jsonschema >=3
    - numpy
    - typing_extensions

test:
  requires:
    - pytest
    - pydantic >=2.6
  imports:
    - event_model
  commands:
    - pytest --pyargs event_model.tests

about:
  home: https://github.com/bluesky/event-model
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Data model for event-based data collection and analysis

extra:
  recipe-maintainers:
    - danielballan
    - mrakitin
    - stuartcampbell
    - tacaswell
    - gwbischof
