{% set name = "event-model" %}
{% set version = "1.23.1" %}
{% set sha256 = "5bb70fd8c7f345aa32afe561aff5a306b2c8a19cbdc3066b736643c8092ddaab" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - importlib-resources
    - jsonschema >=3
    - numpy
    - typing_extensions

test:
  requires:
    - pytest
    - pydantic >=2.6
    - python {{ python_min }}
    - datamodel-code-generator
  imports:
    - event_model
  commands:
    - python -m event_model.generate
    - pytest --pyargs event_model.tests

about:
  home: https://github.com/bluesky/event-model
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Data model for event-based data collection and analysis

extra:
  recipe-maintainers:
    - danielballan
    - mrakitin
    - stuartcampbell
    - tacaswell
    - gwbischof
