{% set version = "1.6.0" %}

package:
    name: event-model
    version: {{ version }}

source:
    url: https://github.com/NSLS-II/event-model/archive/v{{ version }}.tar.gz
    fn: event-model-v{{version}}.tar.gz
    sha256: 6e44d32b84b39935ae51e4b72179d7b93f9078b568aa2be882c53b42d2d0b586

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - enum34  # [py2k]
        - setuptools

test:
    imports:
        - event_model

about:
    home: https://github.com/NSLS-II/event-model
    license: BSD 3-Clause
    summary: data model for event-based data collection and analysis

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
        - CJ-Wright
