{% set name = "event-model" %}
{% set version = "1.23" %}
{% set sha256 = "7481cc97151b3ac77b5f5c6a11daf24c9c5d56bf58c88f4318f393e9a804f598" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    0001-MNT-restore-missing-__init__.py-from-tests-module

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - jsonschema >=3
    - numpy
    - typing_extensions

test:
  requires:
    - pytest
    - pydantic >=2.6
    - python {{ python_min }}
  imports:
    - event_model
  commands:
    - pytest --pyargs event_model.tests

about:
  home: https://github.com/bluesky/event-model
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Data model for event-based data collection and analysis

extra:
  recipe-maintainers:
    - danielballan
    - mrakitin
    - stuartcampbell
    - tacaswell
    - gwbischof
