{% set name = "event-model" %}
{% set version = "1.19.6" %}
{% set sha256 = "3f3d765348cd815abe0a9f7940ffd4c93d2b476a2e5ac8810987b01fc0b88a74" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - schema_relpath.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - jsonschema
    - numpy

test:
  requires:
    - pytest
    - pydantic <2.0
  imports:
    - event_model
  commands:
    - pytest --pyargs event_model.tests

about:
  home: https://github.com/bluesky/event-model
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Data model for event-based data collection and analysis

extra:
  recipe-maintainers:
    - danielballan
    - mrakitin
    - stuartcampbell
    - tacaswell
    - gwbischof
